const pages={
contact:['Contact us','Talk with a real person','Our support team is available Monday–Friday, 8am–6pm.','Phone: 1 800 555 0126|Email: hello@trueprint.shop|Address: 124 Thread Street, Madeville, NY 10001'],
faq:['Frequently asked questions','Ordering and customisation','Choose a product, select your options and send us your artwork. Our team will confirm the details before production.','Production normally begins after payment and artwork approval.|Colour and placement proofs are provided when required.|Custom products are made specifically for your order.'],
shipping:['Shipping policy','Production and delivery','Standard production time is 5–10 business days after payment and artwork approval. Shipping time is separate from production time.','Tracking is provided once an order ships.|Delivery estimates depend on the selected carrier and destination.|Customers are responsible for accurate delivery information.'],
refunds:['Refund policy','Custom orders','Because customised products are made specifically for each customer, custom products are final sale.','Production errors must be reported within five business days of delivery.|Approved issues will be reviewed by our customer care team.'],
privacy:['Privacy policy','Your information','We use order and contact information only to provide products, support and essential shop services.','We do not sell personal information.|Payment details are handled by the checkout provider.|Contact us to request account assistance.'],
terms:['Terms and conditions','Using True Print Shop','Orders enter production after payment and final artwork approval. Customers are responsible for having permission to reproduce submitted artwork.','Colours may vary slightly between screens and finished materials.|Production timing is estimated and may vary by order complexity.'],
about:['About us','Precision in every stitch','True Print Shop creates premium custom apparel with reliable materials, careful decoration and in-house attention to detail.','Made in-house.|Premium embroidery.|Built to last.'],
blog:['Blog','Ideas, guides and shop updates','Practical advice for choosing garments, preparing artwork and getting better results from custom print and embroidery.','Choosing the right blank for your project.|How to prepare artwork.|Embroidery versus print.'],
careers:['Careers','Make great work with us','We are building a team that cares about craft, service and dependable custom apparel.','Production and finishing.|Customer care.|Design and prepress.']
};
const key=new URLSearchParams(location.search).get('page')||'contact',data=pages[key]||pages.contact;document.title=`${data[0]} — True Print Shop`;document.getElementById('info-title').textContent=data[0];document.getElementById('info-content').innerHTML=`<h2>${data[1]}</h2><p>${data[2]}</p><ul>${data[3].split('|').map(item=>`<li>${item}</li>`).join('')}</ul>`;
